os:
- linux
sudo: true
language:
- c
before_install:
  - sudo apt-get -qq update
  - sudo apt-get install -y cmake libapr1-dev libaprutil1-dev doxygen
before_script:
- mkdir build
- cd build
- cmake -DCMAKE_BUILD_TYPE=RELEASE ..
script:
- make all