os:
  - linux
  - osx

sudo: true
language:
  - c
before_install:
  - if [[ "$TRAVIS_OS_NAME" == "osx" ]]; then brew update ; fi
  - if [[ "$TRAVIS_OS_NAME" == "osx" ]]; then brew install apr apr-util doxygen ; fi
before_script:
  - mkdir build
  - cd build
  - cmake -DCMAKE_BUILD_TYPE=RELEASE ..
script:
  - make all

addons:
  apt:
    packages:
      - libapr1-dev
      - libaprutil1-dev
      - doxygen
